apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: openai-ui
  name: openai-ui
  namespace: openai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openai-ui
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: openai-ui
    spec:
      containers:
        - image: ghcr.io/fhswf/openai-ui:0.18.8
          name: ui
          ports:
            - containerPort: 80
          env:
            - name: VITE_RELEASE
              value: 0.18.8
            - name: VITE_BUILD_SHA
              value: 435e7afb3f7c0ad78abb4dbc6cf7295a0e5051a3
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
            requests:
              memory: 128Mi
              cpu: 500m
      restartPolicy: Always
status: {}
