apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: openai-ui
  name: openai-ui
  namespace: openai-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openai-ui
  strategy:
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        io.kompose.service: openai-ui
    spec:
      containers:
        - image: ghcr.io/fhswf/openai-ui:0.20.0
          name: ui
          ports:
            - containerPort: 80
          env:
            - name: VITE_RELEASE
              value: 0.20.0
            - name: VITE_BUILD_SHA
              value: 8e1c4acfc64eefa5c25e551c0beb53d680f4dc11
          resources:
            limits:
              memory: 256Mi
              cpu: 1000m
            requests:
              memory: 128Mi
              cpu: 500m
      restartPolicy: Always
status: {}
