---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirectscheme
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  name: openai.fh-swf.cloud-frontend
  namespace: openai-proxy
spec:
  rules:
  - host: openai.fh-swf.cloud
    http:
      paths:
      - backend:
          service:
            name: openai-ui
            port:
              number: 80
        path: /
        pathType: Prefix   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.frontend.passHostHeader: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
  name: openai.ki.fh-swf.de-frontend
  namespace: openai-proxy
spec:
  rules:
  - host: openai.ki.fh-swf.de
    http:
      paths:
      - backend:
          service:
            name: openai-ui
            port:
              number: 80
        path: /
        pathType: Prefix   